variables:
  PYTHON_VERSION: "3.14"

include:
  - component: $CI_SERVER_FQDN/nerdycraft/shared-ci/python@main
  - component: $CI_SERVER_FQDN/nerdycraft/shared-ci/docker@main
    inputs:
      build-args: --build-arg PYTHON_VERSION=${PYTHON_VERSION}
      version-build-arg: VERSION
      test-command: "python -m pandaproxy --version"
      rebuild-paths:
        - pyproject.toml
        - uv.lock
        - src/**/*
        - .gitlab-ci.yml
  - component: $CI_SERVER_FQDN/nerdycraft/shared-ci/release-badge@main
