include:
  - project: nerdycraft/shared-ci
    ref: main
    file:
      - /templates/lint.yml
      - /templates/test.yml
      - /templates/docker.yml
      - /templates/pr-agent.yml
      - /templates/release-badge.yml
